package:
  name: h5unixpipe
  version: 0.0.0

requirements:
  build:
    - python 2.7*
    - hdf5_cxx
    - minimal-traceback
  run:
    - hdf5_cxx
    - minimal-traceback

source:
  git_url: https://github.com/dfroger/h5unixpipe

build:
  number: 1
  binary_relocation: true

about:
  home: https://github.com/dfroger/h5unixpipe
  license: GPL
